apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-lt3w
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-lt3w
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-lt3w
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-lt3w
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-lt3w
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dvru-tenant/rhtap-demo-app/hacbs-test-project-lt3w@sha256:927ee116f82b0011f4038362e4635fcb9d00c76d6d17206ade7df5598399ac22
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
