apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-lt3w
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dvru-tenant/rhtap-demo-app/hacbs-test-project-lt3w@sha256:a410258884f4202b94d70ed4d8e0be92e9a7294e9b44efb28154749dc978c384
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
